name: flutter_unit
description: A new Flutter application.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

parameters:

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

  copy_with_extension: ^2.0.2

  equatable: ^2.0.3

#  autoequal: ^0.2.0

  flutter_bloc: ^7.1.0

  flutter_markdown: ^0.6.2

  flutter_screenutil: ^5.0.0+2

  collection: ^1.15.0

  ffi: ^1.1.2

  fimber: ^0.6.1

  native_add:
    path: native_add

  opencv_plugin:
    path: opencv_plugin
#  TODO : aspectd 未迁移到 null 安全
#  aspectd_impl:
#    path: aspectd_impl


dev_dependencies:
  flutter_test:
    sdk: flutter

#  autoequal_gen: ^0.2.0
  build_runner: ^2.1.2
  copy_with_extension_gen: ^2.0.2
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/design/