name: flutter_unit
description: A new Flutter application.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

parameters:
# private_pub_server: &private_pub_server "http://pubserver:7878"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

  copy_with_extension: ^2.0.0

  equatable: ^2.0.0

  autoequal: ^0.2.0

  flutter_bloc: ^7.1.0

  flutter_markdown: ^0.6.2

  flutter_screenutil: ^5.0.0+2

  #  jd_face:
  #    version: 0.0.3+1
  #    hosted:
  #      name: jd_face
  #      url: *private_pub_server
  ffi: ^1.1.2

  fimber: ^0.6.1

  native_add:
    path: native_add

  opencv_plugin:
    path: opencv_plugin
#  TODO : aspectd 未迁移到 null 安全
#  aspectd_impl:
#    path: aspectd_impl

dev_dependencies:
  flutter_test:
    sdk: flutter

  autoequal_gen: ^0.2.0
  build_runner: ^1.11.5
  copy_with_extension_gen: ^2.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/