name: flutter_unit
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

parameters:
  private_pub_server: &private_pub_server "http://pubserver:7878"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  equatable: ^2.0.0

  flutter_bloc: ^7.0.0

  flutter_markdown: ^0.6.2

  flutter_screenutil: ^5.0.0+2

  #  jd_face:
  #    version: 0.0.3+1
  #    hosted:
  #      name: jd_face
  #      url: *private_pub_server


  native_add:
    path: native_add

  opencv_plugin:
    path: opencv_plugin

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/